### PR TITLE
Player prefab fix

### PR DESCRIPTION
**Pull request by alarson892**
Player prefab no longer reports any errors when collection coins

### CODE REVIEW

**Review by clarson99 — CHANGES_REQUESTED** [review]
You didnt resolve your merge conflicts correctly, this file is probably corrupt.  The lines that start with three dashes like `---` and `=======` were modified by git.  Git uses the dashes and equal signs to show which lines are in conflict.  You'll need to go learn about git merge conflicts and how to resolve them, then you will need to modify these files to remove the conflict markers.  

Let me know if you want to pair up for this, the first time resolving a merge conflict can be pretty confusing.

**Comment by alarson892** [comment]
I don't think `---` is a conflict marker. I found this:
[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github](url)
I think the Player prefab was broken when I merged #11 , since I'd modified the same file in #10, which was out at the same time. That's when I messed up the conflict resolution. The newly changed-files should merge with no issue. Everything on this branch works as it should.

**Comment by clarson99** [comment]
Yeah after a closer look I think you are right.  I made an incorrect assumption when I saw a bunch of '---' in the commit. I did not expect a string like that to be valid syntax in the file, my bad.

**Review by clarson99 — APPROVED** [review]
Lgtm

**Pull request merged**
